#!/bin/bash

echo "Running..."

# eval "$(micromamba shell hook --shell bash)"

# echo "micromamba loaded"
SUBMIT_DIR=$(pwd)

tar -xzf source.tar.gz
cd synthetic_shg || exit 1


pip install matplotlib
pip install --upgrade scipy
#export CONDA_ALWAYS_YES="true"

# 2. Tell conda that the ToS has been acknowledged for this session
#export CONDA_TOS_ACK="true"

#conda tos accept --override-channels --channel https://anaconda.com
#conda tos accept --override-channels --channel https://anaconda.com

#sed -i 's/- defaults/- conda-forge/g' environment.yml
#sed -i 's|- https://repo.anaconda.com/pkgs/main|- conda-forge|g' environment.yml
#sed -i 's|- https://repo.anaconda.com/pkgs/r|- conda-forge|g' environment.yml

# Place the channel overrides BEFORE specifying the file
#conda env create --override-channels -c conda-forge -f environment.yml --yes

# 2. Build the environment silently using ONLY the forge channel
#micromamba env create -f environment.yml
#micromamba activate neural_inference
#conda env create -f environment.yml -y
#source activate nest_env

mkdir data

# pip install matplotlib

# micromamba run -n base python generate_data.py
python3 generate_data.py test -n 2

if compgen -G "*.npz" > /dev/null; then
    mv *.npz data/
else
    echo "Warning: No .npz files were generated by the script!"
fi

tar -czf "$SUBMIT_DIR/data.tar.gz" data

echo "Done"